### PR TITLE
Fix false positive due to local variable deep assign

### LINKED ISSUE #59: Deep assign to local variables causes false positives
NilAway currently does not allow deep nilability assignment to local variables, which results in false positives.

```
func testDeepAssignNil() {
   m := make(map[int]*string)
   m[0] = nil // FP: error reported here not allowing nil to be assigned
   if v, ok := m[0]; ok && v != nil {
       _ = *v
   }
} 
```

### PR DESCRIPTION
**Pull request by sonalmahajan15**
NilAway puts a restriction on deep nilable assignment to local variables. This can result in false positives, if the dereferences are properly guarded. This PR lifts this restriction and allows deep nilability into local variables, thereby addressing the false positives.

[closes #59]
[depends on #82 ]

### CODE REVIEW

File: annotation/key.go [hunk 1]
```diff
@@ -455,6 +455,38 @@ func (gk *GlobalVarAnnotationKey) String() string {
 	return fmt.Sprintf("Global Variable %s", gk.VarDecl.Name())
 }
 
+// LocalVarAnnotationKey allows the Lookup of a global variable's annotations in the Annotation Map
```
Comment (yuxincs) [inline annotation/key.go:458]:
```suggestion
// LocalVarAnnotationKey allows the Lookup of a local variable's annotations in the Annotation Map
```

right?

**Review by yuxincs — APPROVED** [review]
Nice find with a simple but great fix!

I only have a suggestion on a doc fix 😄

File: annotation/key.go (hunk 1 above)
Comment (sonalmahajan15) [reply annotation/key.go]: Yes! Good catch :)
