### PR TITLE
Fix NilAway FPs on channel sends/receives

### LINKED ISSUE #98: False positive for a nil channel select case
Although a direct send/receive on a nil channel can cause a panic, the following code with use of `select` is safe. However, NilAway still reports an error.

```
func foo(aChan, bChan chan string) {
	aChan <- "abc"
	bChan <- "xyz"

	if true {
		aChan = nil
	}

	select {
	case a := <-aChan:   // error: "literal `nil` uninitialized; nil channel accessed"
		print(a)
	case b := <-bChan:
		print(b)
	}
}

func test() {
	aChan := make(chan string)
	bChan := make(chan string)

	go foo(aChan, bChan)
}
```

### LINKED ISSUE #167: Receiving from channel is mistakenly checked
as the spec says "Receiving from a nil channel blocks forever." https://go.dev/ref/spec#Receive_operator

But in code we treat it as panic

https://github.com/uber-go/nilaway/blob/2f6a74d7c0e26d87215dfbda2c9ab5acbb64b11c/assertion/function/assertiontree/root_assertion_node.go#L812C1-L813C1

This solves https://github.com/uber-go/nilaway/issues/98

### PR DESCRIPTION
**Pull request by yuxincs**
See issue #192 for a more detailed discussion on handling channels in NilAway. To make this PR more self-contained, below is a partial copy of the discussion there:

See the following behaviors regarding nil / closed channels (taken from [this SO post](https://stackoverflow.com/questions/43616434/closed-channel-vs-nil-channel), slightly modified): 
> 1. A send to a nil channel blocks forever
> 2. A receive from a nil channel blocks forever
> 3. A send to a closed channel panics
> 4. A receive from a closed channel returns the zero value immediately

Only case 3 (sending to a closed channel) will result in a panic. The other cases arguably may not be within scope of NilAway's analysis. Moreover, NilAway currently only tracks nilabilities of channels, but not the states of them, making it unable to really handle case 2 and 4.

Since this introduces a lot more FPs than TPs (if any), this PR removes logic to require sending to/receiving from nonnil channels. We leave properly handling channels as future work (especially around tracking states of channels).

The test cases have been updated to reflect this. Specifically, we kept the test cases there to now serve as negative cases in case for future development of such a support.

Fixes #98 
Fixes #167

### CODE REVIEW

File: assertion/function/assertiontree/backprop.go [hunk 1]
```diff
@@ -116,13 +116,13 @@ func backpropAcrossNode(rootNode *RootAssertionNode, node ast.Node) error {
...
-		Expr:       node.Chan,
-		Guards:     util.NoGuards(),
-	})
-
+	// Note that for channel sends, we have:
+	// (1) A send to a nil channel blocks forever;
+	// (2) A send to a closed channel panics.
+	// (1) falls out of scope for NilAway and hence we do not create a consumer here for the
+	// channel variable. For (2), since we do not track the state of the channels, we currently
+	// can not support it.
```
Comment (sonalmahajan15) [inline assertion/function/assertiontree/backprop.go:124]:
```suggestion
	// cannot support it.
```

File: assertion/function/assertiontree/root_assertion_node.go [hunk 2]
```diff
@@ -807,15 +807,14 @@ func (r *RootAssertionNode) AddComputation(expr ast.Expr) {
...
-				Guards:     util.NoGuards(),
-			})
-		}
+		// Note if expr.Op == token.ARROW it represents a channel receive (<-X), and we have:
+		// (1) A receive from a nil channel blocks forever;
+		// (2) A receive from a closed channel returns the zero value immediately.
+		// (1) falls out of scope of NilAway, and we have a lot of valid Go code that receives
+		// from nil channels (e.g., select statements with nilable channels). So we do not create
+		// consumer for the channel variable here. For (2), since we currently do not track the
+		// state of channels, we currently can not support it either.
```
Comment (sonalmahajan15) [inline assertion/function/assertiontree/root_assertion_node.go:816]:
```suggestion
		// state of channels, we currently cannot support it either.
```

File: testdata/src/go.uber.org/errormessage/errormessage.go [hunk 3]
```diff
@@ -101,28 +101,22 @@ func test9(m map[int]*int) {
...
+// nilable(nilableChan) nonnil(nonnilDeeplyNonnilChan, <-nonnilDeeplyNonnilChan)
+func test10(nilableChan chan *int, nonnilDeeplyNonnilChan chan *int) {
+	x := 1
+	nilableChan <- &x
+	// Sending nilable values to nonnil and deeply nonnil channels is not OK.
+	var y *int
+	nonnilDeeplyNonnilChan <- y //want "`y` assigned deeply into parameter arg `nonnilDeeplyNonnilChan`"
 }
 
+// nilable(s)
```
Comment (sonalmahajan15) [inline testdata/src/go.uber.org/errormessage/errormessage.go:113]: Unrelated to the PR, I guess, but a welcome change :)

**Review by sonalmahajan15 — APPROVED** [review]
As discussed internally, we did agree upon this strategy to address false positives. LGTM!

File: testdata/src/go.uber.org/errormessage/errormessage.go (hunk 3 above)
Comment (yuxincs) [reply testdata/src/go.uber.org/errormessage/errormessage.go:113]: Yes :)
